#!/usr/bin/env bash
set -euo pipefail

usage() { echo "Usage: $0 --prompt PROMPT.md --out OUT.md [--name NAME]"; exit 2; }

PROMPT="" OUT="" NAME=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --prompt) PROMPT="$2"; shift 2;;
    --out) OUT="$2"; shift 2;;
    --name) NAME="$2"; shift 2;;
    *) usage;;
  esac
done
[[ -z "$PROMPT" || -z "$OUT" ]] && usage

# Defaults (overridden by front-matter)
: "${LLM_MODEL:=bedrock-claude-v4.5-sonnet-us}"

PACK_DIR="build"
DOC_NAME="${NAME:-$(basename "$(dirname "$OUT")")}"
PACK="$PACK_DIR/${DOC_NAME}.promptpack.txt"
PARAMS="$PACK_DIR/${DOC_NAME}.params.json"
TMP_OUT="$PACK_DIR/${DOC_NAME}.tmp"
TMP_ERR="$PACK_DIR/${DOC_NAME}.err"

python3 scripts/ensure_llm.py >/dev/null || true

echo "📝 Rendering: $DOC_NAME" >&2

python3 scripts/pack_prompt.py   --prompt "$PROMPT"   --prev "$OUT"   --out "$PACK"   --params-out "$PARAMS"   --name "$DOC_NAME"

# Read effective params from front-matter (fallback to env defaults)
MODEL=$(jq -r '.model // empty' "$PARAMS" 2>/dev/null || echo "")
MODEL="${MODEL:-$LLM_MODEL}"

echo "🤖 Using model: $MODEL" >&2

# Gentle retries for transient errors
attempt=0
max_attempts=3
delay=1
while :; do
  set +e
  llm -m "$MODEL" < "$PACK" > "$TMP_OUT" 2> "$TMP_ERR"
  code=$?
  set -e
  if [[ $code -eq 0 ]]; then
    break
  fi

  # Show the actual error on stderr for visibility
  if [[ -s "$TMP_ERR" ]]; then
    echo "Error calling LLM (attempt $((attempt+1))/$max_attempts):" >&2
    cat "$TMP_ERR" >&2

    # Check for common errors and provide actionable advice
    if grep -q "ExpiredToken" "$TMP_ERR" 2>/dev/null; then
      echo "" >&2
      echo "💡 AWS credentials expired. To fix:" >&2
      echo "   - Run: aws sso login" >&2
      echo "   - Or refresh your AWS_SESSION_TOKEN in .env" >&2
    elif grep -q "authentication\|credentials" "$TMP_ERR" 2>/dev/null; then
      echo "" >&2
      echo "💡 Authentication issue. Check your .env file and LLM credentials." >&2
    fi
  fi

  if [[ $attempt -ge $((max_attempts-1)) ]]; then
    echo "" >&2
    echo "❌ Failed after $max_attempts attempts. Giving up." >&2
    exit $code
  fi

  attempt=$((attempt+1))
  echo "Retrying in ${delay}s..." >&2
  sleep $delay
  delay=$((delay*2))
done

# Verify output file was created
if [[ ! -f "$TMP_OUT" ]]; then
  echo "❌ Error: LLM succeeded but produced no output file" >&2
  exit 1
fi

# Stamp footer with model + git sha + date
SIG=$(sha256sum < "$PACK" | awk '{print $1}')
REV=$(git rev-parse --short HEAD 2>/dev/null || echo "workspace")
DATE=$(date -u +%F)
{
  echo "<!-- Generated by Graft | model=${MODEL} | sig=${SIG} | rev=${REV} | ${DATE} -->"
  # Strip any existing Graft comments from LLM output, then output the content
  grep -v "^<!-- Generated by Graft" "$TMP_OUT" 2>/dev/null || cat "$TMP_OUT"
} > "$OUT"

# Clean up temporary files on success
rm -f "$TMP_OUT" "$TMP_ERR"

echo "✅ Completed: $DOC_NAME" >&2
