#!/usr/bin/env bash
set -euo pipefail

usage() { echo "Usage: $0 --prompt PROMPT.md --out OUT.md [--name NAME]"; exit 2; }

PROMPT="" OUT="" NAME=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --prompt) PROMPT="$2"; shift 2;;
    --out) OUT="$2"; shift 2;;
    --name) NAME="$2"; shift 2;;
    *) usage;;
  esac
done
[[ -z "$PROMPT" || -z "$OUT" ]] && usage

# Defaults (overridden by front-matter)
: "${LLM_MODEL:=bedrock-claude-v4.5-sonnet-us}"

PACK_DIR="build"
DOC_NAME="${NAME:-$(basename "$(dirname "$OUT")")}"
PACK="$PACK_DIR/${DOC_NAME}.promptpack.txt"
PARAMS="$PACK_DIR/${DOC_NAME}.params.json"
TMP_OUT="$PACK_DIR/${DOC_NAME}.tmp"
TMP_ERR="$PACK_DIR/${DOC_NAME}.err"

python3 scripts/ensure_llm.py >/dev/null || true

python3 scripts/pack_prompt.py   --prompt "$PROMPT"   --prev "$OUT"   --out "$PACK"   --params-out "$PARAMS"   --name "$DOC_NAME"

# Read effective params from front-matter (fallback to env defaults)
MODEL=$(jq -r '.model // empty' "$PARAMS" 2>/dev/null || echo "")
MODEL="${MODEL:-$LLM_MODEL}"

# Gentle retries for transient errors
attempt=0
max_attempts=3
delay=1
while :; do
  set +e
  llm -m "$MODEL" < "$PACK" > "$TMP_OUT" 2> "$TMP_ERR"
  code=$?
  set -e
  if [[ $code -eq 0 ]]; then
    break
  fi
  if [[ $attempt -ge $((max_attempts-1)) ]]; then
    echo "Model invocation failed after $max_attempts attempts. See $TMP_ERR" >&2
    exit $code
  fi
  attempt=$((attempt+1))
  sleep $delay
  delay=$((delay*2))
done

# Stamp footer with model + git sha + date
SIG=$(sha256sum < "$PACK" | awk '{print $1}')
REV=$(git rev-parse --short HEAD 2>/dev/null || echo "workspace")
DATE=$(date -u +%F)
{
  echo "<!-- Generated by Docflow | model=${MODEL} | sig=${SIG} | rev=${REV} | ${DATE} -->"
  # Strip any existing Docflow comments from LLM output
  grep -v "^<!-- Generated by Docflow" "$TMP_OUT" || cat "$TMP_OUT"
} > "$OUT"

# Clean up temporary files on success
rm -f "$TMP_OUT" "$TMP_ERR"
